require('dotenv').config();
const express=require('express'),cors=require('cors'),axios=require('axios'),nodemailer=require('nodemailer'),Imap=require('imap'),{simpleParser}=require('mailparser'),cron=require('node-cron'),path=require('path'),fs=require('fs'),low=require('lowdb'),FileSync=require('lowdb/adapters/FileSync');
const DATA_DIR=path.join(__dirname,'data');
if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});
const db=low(new FileSync(path.join(DATA_DIR,'leadforge.json')));
db.defaults({leads:[],contacts:[],emails:[],activity_log:[],_nextId:{leads:1,contacts:1,emails:1,activity_log:1}}).write();
function nextId(t){const id=db.get(`_nextId.${t}`).value();db.set(`_nextId.${t}`,id+1).write();return id;}
function getAllLeads(){return db.get('leads').value().map(l=>{const c=db.get('contacts').filter({lead_id:l.id}).value();return{...l,contact_count:c.length,total_sent:c.reduce((a,x)=>a+(x.emails_sent||0),0),has_reply:c.some(x=>x.status==='replied')?1:0};}).reverse();}
function getLeadById(id){return db.get('leads').find({id:Number(id)}).value();}
function insertLead(d){const id=nextId('leads');db.get('leads').push({id,company:d.company||'',website:d.website||null,industry:d.industry||null,size:d.size||null,location:d.location||null,source:d.source||'manual',notes:d.notes||null,status:'new',created_at:new Date().toISOString(),updated_at:new Date().toISOString()}).write();return{lastInsertRowid:id};}
function getContactsByLeadId(lid){return db.get('contacts').filter({lead_id:Number(lid)}).value();}
function getContactById(id){return db.get('contacts').find({id:Number(id)}).value();}
function insertContact(d){const id=nextId('contacts');db.get('contacts').push({id,lead_id:Number(d.lead_id),name:d.name||'Unknown',first_name:d.first_name||'there',role:d.role||'',email:d.email||null,linkedin:d.linkedin||null,status:'new',emails_sent:0,last_sent:null,replied_at:null,created_at:new Date().toISOString()}).write();return{lastInsertRowid:id};}
function updateContactEmail(id,email){db.get('contacts').find({id:Number(id)}).assign({email}).write();}
function markContactSent(id){const c=db.get('contacts').find({id:Number(id)}).value();if(!c)return;db.get('contacts').find({id:Number(id)}).assign({emails_sent:(c.emails_sent||0)+1,last_sent:new Date().toISOString(),status:c.status==='new'?'sent':'followup'}).write();}
function markContactReplied(id){db.get('contacts').find({id:Number(id)}).assign({status:'replied',replied_at:new Date().toISOString()}).write();}
function getContactsDueForFollowup(){const days=(process.env.FOLLOWUP_DAYS||'3,7,14').split(',').map(Number),min=Math.min(...days);return db.get('contacts').filter(c=>['sent','followup'].includes(c.status)&&c.email&&c.last_sent&&c.emails_sent<days.length+1&&(Date.now()-new Date(c.last_sent).getTime())/86400000>=min).value().map(c=>{const l=getLeadById(c.lead_id);return{...c,company:l?l.company:''};});}
function getContactsNotYetEmailed(){return db.get('contacts').filter(c=>c.status==='new'&&c.email).value().slice(0,parseInt(process.env.MAX_EMAILS_PER_DAY)||30).map(c=>{const l=getLeadById(c.lead_id);return{...c,company:l?l.company:''};});}
function getEmailsByLeadId(lid){return db.get('emails').filter({lead_id:Number(lid)}).value().map(e=>{const c=getContactById(e.contact_id);return{...e,contact_name:c?c.name:'',contact_role:c?c.role:''};});}
function insertEmail(d){const id=nextId('emails');db.get('emails').push({id,contact_id:Number(d.contact_id),lead_id:Number(d.lead_id),direction:d.direction,subject:d.subject||'',body:d.body||'',from_addr:d.from_addr||'',to_addr:d.to_addr||'',template_num:d.template_num||null,message_id:d.message_id||null,sent_at:new Date().toISOString()}).write();return{lastInsertRowid:id};}
function dbLog(icon,title,detail){console.log(`[${icon}] ${title}${detail?' — '+detail:''}`);const id=nextId('activity_log');db.get('activity_log').push({id,icon,title,detail:detail||'',created_at:new Date().toISOString()}).write();}
function getRecentActivity(limit=50){return db.get('activity_log').value().slice(-limit).reverse();}
function getStats(){const l=db.get('leads').value(),c=db.get('contacts').value(),e=db.get('emails').value();return{total_leads:l.length,total_contacts:c.length,emails_found:c.filter(x=>x.email).length,contacted:c.filter(x=>x.emails_sent>0).length,total_sent:c.reduce((a,x)=>a+(x.emails_sent||0),0),followups_due:c.filter(x=>x.status==='followup').length,total_replies:c.filter(x=>x.status==='replied').length,emails_out:e.filter(x=>x.direction==='out').length};}
const TPLS={1:{sub:'IT Staff Augmentation for {{company_name}}?',body:'Hi {{first_name}},\n\nI noticed {{company_name}} is actively building its tech team.\n\nWe help US companies staff up with pre-vetted IT professionals (React, Node.js, Python, DevOps, QA) ready in 5–7 business days — 40–60% less than full-time hiring.\n\nOpen to a quick 15-min call this week?\n\nBest,\n{{your_name}}\n{{your_company}}\n{{your_phone}} · {{your_website}}'},2:{sub:'Re: IT Staff Augmentation for {{company_name}}?',body:'Hi {{first_name}},\n\nFollowing up — we recently helped a SaaS company stand up a 3-person React + Node team in under a week.\n\nWorth a 15-min call?\n\n{{your_name}}\n{{your_company}}'},3:{sub:'One more thought — {{company_name}}',body:'Hi {{first_name}},\n\nOur clients say the biggest win is scaling back down just as fast — no layoffs, no notice periods.\n\nHappy to send a one-pager.\n\n{{your_name}}\n{{your_company}}'},4:{sub:'Closing the loop — {{company_name}}',body:'Hi {{first_name}},\n\nI\'ll leave it here — if IT staffing needs come up, feel free to reach out anytime.\n\nWishing {{company_name}} all the best.\n\n{{your_name}}\n{{your_company}}'}};
function fillTpl(t,v){let s=t.sub,b=t.body;for(const[k,val]of Object.entries(v)){s=s.replaceAll(`{{${k}}}`,val||'');b=b.replaceAll(`{{${k}}}`,val||'');}return{subject:s,body:b};}
function makeTransport(){return nodemailer.createTransport({host:process.env.SMTP_HOST||'smtp.hostinger.com',port:parseInt(process.env.SMTP_PORT)||465,secure:(process.env.SMTP_PORT||'465')==='465',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS},connectionTimeout:10000,greetingTimeout:10000,socketTimeout:10000});}
async function testSmtp(){try{await makeTransport().verify();dbLog('✅','SMTP connected',process.env.SMTP_USER);return{ok:true};}catch(e){dbLog('❌','SMTP failed',e.message);return{ok:false,error:e.message};}}
async function sendEmail({contact,lead,emailNum=1,dryRun=false}){const t=TPLS[emailNum]||TPLS[1];const{subject,body}=fillTpl(t,{first_name:contact.first_name||contact.name?.split(' ')[0]||'there',company_name:lead.company,role:contact.role,your_name:process.env.SMTP_FROM_NAME||'Your Name',your_company:process.env.YOUR_COMPANY||'',your_phone:process.env.YOUR_PHONE||'',your_website:process.env.YOUR_WEBSITE||''});if(dryRun){dbLog('👁','DRY RUN',`To:${contact.email}|${subject}`);return{ok:true,dryRun:true,subject,body};}try{const info=await makeTransport().sendMail({from:`"${process.env.SMTP_FROM_NAME}"<${process.env.SMTP_USER}>`,to:contact.email,subject,text:body});insertEmail({contact_id:contact.id,lead_id:lead.id||contact.lead_id,direction:'out',subject,body,from_addr:process.env.SMTP_USER,to_addr:contact.email,template_num:emailNum,message_id:info.messageId});markContactSent(contact.id);dbLog('📤',`Email #${emailNum} sent`,`${lead.company}→${contact.name}`);return{ok:true,messageId:info.messageId};}catch(e){dbLog('❌','Send failed',e.message);return{ok:false,error:e.message};}}
async function sendNotif({contactName,companyName,replyBody}){if(!process.env.NOTIFY_EMAIL)return;try{await makeTransport().sendMail({from:`"LeadForge"<${process.env.SMTP_USER}>`,to:process.env.NOTIFY_EMAIL,subject:`Reply from ${companyName} — ${contactName}`,text:`New reply!\n\nCompany:${companyName}\nContact:${contactName}\n\n${replyBody||''}`});}catch(e){}}
function delay(s){return new Promise(r=>setTimeout(r,Math.max(5000,(s+(Math.random()-.5)*60)*1000)));}
async function importLeadsFromApollo(){const titles=(process.env.APOLLO_TITLES||'CTO,VP Engineering,IT Manager,HR Director').split(',').map(t=>t.trim());try{dbLog('🔍','Apollo search','Searching...');const res=await axios.post('https://api.apollo.io/v1/mixed_people/search',{page:1,per_page:parseInt(process.env.MAX_LEADS_PER_RUN)||20,person_titles:titles,organization_locations:[process.env.APOLLO_COUNTRY||'United States'],organization_num_employees_ranges:[`${process.env.APOLLO_MIN_EMPLOYEES||10},${process.env.APOLLO_MAX_EMPLOYEES||500}`],contact_email_status:['verified','likely to engage']},{headers:{'Content-Type':'application/json','X-Api-Key':process.env.APOLLO_API_KEY}});const people=res.data.people||[];const byCompany={};for(const p of people){const co=p.organization?.name;if(!co)continue;if(!byCompany[co])byCompany[co]={org:p.organization,people:[]};byCompany[co].people.push(p);}const maxC=parseInt(process.env.CONTACTS_PER_COMPANY)||2;let la=0,ca=0;for(const[coName,{org,people}]of Object.entries(byCompany)){const r=insertLead({company:coName,website:org?.website_url||null,industry:org?.industry||null,size:org?.num_employees?`${org.num_employees} employees`:null,location:org?.city?`${org.city}, ${org.country||''}`:null,source:'apollo',notes:'Apollo.io import'});la++;for(const p of people.slice(0,maxC)){const np=(p.name||'').split(' ');insertContact({lead_id:r.lastInsertRowid,name:p.name||'Unknown',first_name:np[0]||'there',role:p.title||'',email:p.email||null,linkedin:p.linkedin_url||null});ca++;}}dbLog('🚀','Apollo done',`${la} companies, ${ca} contacts`);return{leadsAdded:la,contactsAdded:ca};}catch(e){dbLog('❌','Apollo failed',e.response?.data?.error||e.message);throw e;}}
async function checkForReplies(){return new Promise(resolve=>{const imap=new Imap({user:process.env.SMTP_USER,password:process.env.SMTP_PASS,host:process.env.IMAP_HOST||'imap.hostinger.com',port:993,tls:true,tlsOptions:{rejectUnauthorized:false},connTimeout:15000,authTimeout:15000});let found=0;imap.once('ready',()=>{imap.openBox('INBOX',false,(err)=>{if(err){imap.end();return resolve(0);}const since=new Date();since.setDate(since.getDate()-30);imap.search(['UNSEEN',['SINCE',since.toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'})]],async(err,uids)=>{if(err||!uids?.length){imap.end();return resolve(0);}const fetch=imap.fetch(uids,{bodies:'',markSeen:false});const promises=[];fetch.on('message',msg=>{const p=new Promise(res=>{let buf='';msg.on('body',s=>s.on('data',d=>buf+=d.toString()));msg.once('end',async()=>{try{const parsed=await simpleParser(buf);const fe=parsed.from?.value?.[0]?.address?.toLowerCase();if(!fe)return res();const contact=db.get('contacts').filter(c=>c.email&&c.email.toLowerCase()===fe).value()[0];if(contact&&contact.status!=='replied'){found++;markContactReplied(contact.id);const lead=getLeadById(contact.lead_id);insertEmail({contact_id:contact.id,lead_id:contact.lead_id,direction:'in',subject:parsed.subject||'',body:parsed.text||'',from_addr:fe,to_addr:process.env.SMTP_USER,template_num:null,message_id:parsed.messageId||null});dbLog('💬','REPLY!',`${lead?.company}—${contact.name}`);await sendNotif({contactName:contact.name,companyName:lead?.company||'',replyBody:(parsed.text||'').substring(0,500)});}}catch(e){}res();});});promises.push(p);});fetch.once('end',async()=>{await Promise.all(promises);imap.end();resolve(found);});});});});imap.once('error',()=>resolve(0));imap.once('end',()=>{});imap.connect();});}
let agentRunning=false;
async function runAgentCycle({dryRun=false}={}){if(agentRunning)return;agentRunning=true;dbLog('⚡','Agent started',dryRun?'DRY RUN':'LIVE');try{const r=await checkForReplies();if(r>0)dbLog('🎉',`${r} replies`,'');try{await importLeadsFromApollo();}catch(e){}const nc=getContactsNotYetEmailed();let sent=0;const max=parseInt(process.env.MAX_EMAILS_PER_DAY)||30;for(const c of nc){if(sent>=max)break;const l=getLeadById(c.lead_id);if(!l)continue;const res=await sendEmail({contact:c,lead:l,emailNum:1,dryRun});if(res.ok)sent++;if(!dryRun)await delay(parseInt(process.env.EMAIL_DELAY_SECONDS)||90);}const fc=getContactsDueForFollowup();for(const c of fc){if(sent>=max)break;const l=getLeadById(c.lead_id);if(!l)continue;const res=await sendEmail({contact:c,lead:l,emailNum:Math.min(c.emails_sent+1,4),dryRun});if(res.ok)sent++;if(!dryRun)await delay(parseInt(process.env.EMAIL_DELAY_SECONDS)||90);}dbLog('✅','Cycle done',`${sent} emails`);}catch(e){dbLog('❌','Agent error',e.message);}finally{agentRunning=false;}}
function startScheduler(){cron.schedule('0 9 * * 1-5',()=>runAgentCycle());cron.schedule('0 14 * * 1-5',()=>runAgentCycle());cron.schedule('*/15 * * * *',()=>checkForReplies());dbLog('📅','Scheduler active','9am+2pm weekdays, reply check every 15min');}
const app=express();
app.use(cors());app.use(express.json());
app.get('/healthz',(req,res)=>res.status(200).send('OK'));
app.get('/api/stats',(req,res)=>res.json(getStats()));
app.get('/api/leads',(req,res)=>res.json(getAllLeads()));
app.get('/api/leads/:id',(req,res)=>{const l=getLeadById(req.params.id);if(!l)return res.status(404).json({error:'Not found'});res.json({...l,contacts:getContactsByLeadId(l.id),thread:getEmailsByLeadId(l.id)});});
app.post('/api/leads',(req,res)=>{const{company,website,industry,size,location,source,notes,contacts}=req.body;if(!company)return res.status(400).json({error:'company required'});const r=insertLead({company,website,industry,size,location,source:source||'manual',notes});const lid=r.lastInsertRowid;if(contacts?.length)for(const c of contacts)if(c.name||c.email)insertContact({lead_id:lid,name:c.name||'Unknown',first_name:c.name?.split(' ')[0]||'there',role:c.role||'',email:c.email||null,linkedin:c.linkedin||null});dbLog('➕','Lead added',company);res.json({ok:true,id:lid});});
app.delete('/api/leads/:id',(req,res)=>{db.get('leads').remove({id:Number(req.params.id)}).write();res.json({ok:true});});
app.patch('/api/contacts/:id/email',(req,res)=>{updateContactEmail(req.params.id,req.body.email);res.json({ok:true});});
app.patch('/api/contacts/:id/replied',(req,res)=>{markContactReplied(req.params.id);res.json({ok:true});});
app.post('/api/contacts/:id/send',async(req,res)=>{const c=getContactById(req.params.id);if(!c)return res.status(404).json({error:'Not found'});if(!c.email)return res.status(400).json({error:'No email'});const l=getLeadById(c.lead_id);res.json(await sendEmail({contact:c,lead:l,emailNum:c.emails_sent+1}));});
app.get('/api/activity',(req,res)=>res.json(getRecentActivity(parseInt(req.query.limit)||50)));
app.post('/api/agent/run',async(req,res)=>{const d=req.body?.dry_run===true;runAgentCycle({dryRun:d}).catch(console.error);res.json({ok:true,message:d?'Dry run started':'Agent started'});});
app.post('/api/agent/check-replies',async(req,res)=>res.json({ok:true,replies_found:await checkForReplies()}));
app.get('/api/test/gmail',async(req,res)=>res.json(await testSmtp()));
app.get('/api/test/apollo',async(req,res)=>{try{await axios.post('https://api.apollo.io/v1/mixed_people/search',{per_page:1},{headers:{'Content-Type':'application/json','X-Api-Key':process.env.APOLLO_API_KEY},timeout:10000});res.json({ok:true,message:'Apollo connected'});}catch(e){res.json({ok:false,error:e.response?.data?.error||e.message});}});
app.post('/api/apollo/import',async(req,res)=>{try{res.json({ok:true,...await importLeadsFromApollo()});}catch(e){res.json({ok:false,error:e.message});}});
const PORT=process.env.PORT||3000;
app.listen(PORT,'0.0.0.0',()=>{console.log(`\n🚀 LeadForge running on port ${PORT}\n`);startScheduler();dbLog('🟢','Server started',`Port ${PORT}`);});
